FROM alpine:3.22

RUN apk add --no-cache openssh-server rsync shadow

COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 0755 /usr/local/bin/entrypoint.sh

EXPOSE 22/tcp

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
