uid = root
gid = root
use chroot = no
max connections = 4
log file = /dev/stdout
pid file = /var/run/rsyncd.pid

[synology]
    path = /data/synology
    comment = Synology Hyper Backup target
    auth users = synobackup
    secrets file = /etc/rsyncd.secrets
    read only = no
    list = yes
